### ISSUE TITLE
There is an error in tune_incepv4.py

### ISSUE THREAD

**Issue by zstbackcourt** [shadySource/Intel-Movidius-Challenge#1]
There is a ':' in code"idx = i*batch_size:i*batch_size+batch_size" in line 108 of tune_incepv4.py,what does this ':'? I think that is an error

**Comment by alecGraves** [comment]
Yeah, thanks. The up-to-date script for fine-tuning is ```finetune.py```
```tune_incepv4.py``` was left in accidentally
